import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <container className="mx-auto">
          <ul>
            <li>
              <Link href="/">
                <a className="hover:text-blue-500">
                  Home
                </a>
              </Link>
            </li>
            <li>
              <Link href="/posts">
                <a className="hover:text-blue-500">
                  Post
                </a>
              </Link>
            </li>
          </ul> 
        </container>
      </main>
    </div>
  )
}
